# Generated by Django 4.1.3 on 2023-06-30 09:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_ourworkprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_client', models.CharField(max_length=50)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
    ]
