# Generated by Django 4.1.3 on 2023-06-30 13:02

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_ourclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OurTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_technology', models.CharField(max_length=50)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Our Technologies',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('category', models.ManyToManyField(to='Company.category')),
                ('technologies', models.ManyToManyField(blank=True, null=True, to='Company.ourtechnology')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_figure', models.IntegerField()),
                ('stat_title', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.service')),
            ],
        ),
        migrations.CreateModel(
            name='RecentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', ckeditor.fields.RichTextField()),
                ('problem_statement', ckeditor.fields.RichTextField()),
                ('solution_offered', ckeditor.fields.RichTextField()),
                ('category', models.ManyToManyField(to='Company.category')),
                ('technologies', models.ManyToManyField(blank=True, null=True, to='Company.ourtechnology')),
            ],
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_featured', models.BooleanField()),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.pricing')),
            ],
        ),
        migrations.AddField(
            model_name='pricing',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.service'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(max_length=50)),
                ('faq_answer', ckeditor.fields.RichTextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.service')),
            ],
        ),
    ]
