# Generated by Django 4.1.3 on 2023-06-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_category_ourtechnology_pricing_service_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='Company.service'),
        ),
    ]
