# Generated by Django 4.1.3 on 2023-06-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_alter_pricing_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingfeature',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_features', to='Company.pricing'),
        ),
    ]
