# Generated by Django 4.1.3 on 2023-06-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_alter_pricingfeature_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Company.service'),
        ),
    ]
