# Generated by Django 4.1.3 on 2023-06-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_alter_stat_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='Company.service'),
        ),
    ]
