# Generated by Django 4.1.3 on 2023-07-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_alter_faq_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentjob',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
