# Generated by Django 4.1.3 on 2023-07-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0012_companyinfo_ourteam_socialurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialurl',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_social', to='Company.companyinfo'),
        ),
        migrations.AlterField(
            model_name='socialurl',
            name='team_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_social', to='Company.ourteam'),
        ),
    ]
