# Generated by Django 4.1.3 on 2023-07-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_alter_socialurl_company_alter_socialurl_team_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialurl',
            old_name='whatsapp_url',
            new_name='github_url',
        ),
    ]
