# Generated by Django 4.1.3 on 2023-07-03 16:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_alter_faq_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
