# Generated by Django 4.1.3 on 2023-11-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0022_socialurl_whatsapp_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corevalue',
            name='pic',
        ),
        migrations.AddField(
            model_name='corevalue',
            name='pic_url',
            field=models.URLField(default='https://img.freepik.com/premium-photo/compass-with-arrow-marks-word-mission_207634-2241.jpg?size=626&ext=jpg&ga=GA1.1.1699289041.1668069491&semt=ais'),
        ),
    ]
