# Generated by Django 4.1.3 on 2023-11-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0024_remove_ourtechnology_logo_ourtechnology_get_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourindustry',
            name='logo',
        ),
        migrations.AddField(
            model_name='ourindustry',
            name='get_logo_url',
            field=models.URLField(default=''),
        ),
    ]
