# Generated by Django 4.1.3 on 2024-01-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0026_remove_companyinfo_page_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentjob',
            name='industry',
            field=models.ManyToManyField(blank=True, null=True, to='Company.ourindustry'),
        ),
        migrations.AddField(
            model_name='recentjob',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
