# Generated by Django 4.1.3 on 2024-01-23 11:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0028_companyinfo_testimonial_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('number_of_openings', models.IntegerField()),
                ('job_title', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('years_of_experience', models.CharField(max_length=225)),
                ('skills', models.CharField(max_length=225)),
                ('roles', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
