# Generated by Django 4.1.3 on 2024-01-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0029_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
