# Generated by Django 4.1.3 on 2024-01-26 15:21

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0031_companyinfo_career_benefits_jobopening_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpeningApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(max_length=255)),
                ('qualification', models.CharField(max_length=225)),
                ('years_of_experience', models.IntegerField()),
                ('cover_letter', cloudinary.models.CloudinaryField(max_length=255)),
                ('resume', cloudinary.models.CloudinaryField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.jobopening')),
            ],
        ),
    ]
